export const endpoint = {
    BASE_URL_STAGING: "http://localhost:3001/",
  
  LOGIN: "api/enterprise/login",
  REGISTER:"api/enterprise/register",
  USER: "api/admin/getUserDetailedList",
  VIDEO: "/api/video/all",
  CHARTBAR: "/api/admin/getMetrics",
  CATEGORY: "api/category/all",
  USER_LIST: "api/admin/getUserDetailedList",
  DISAPPROVAL_USER_LIST: "/api/admin/getDisApprovalUserList",
  FEEDBACK: "/api/admin/getFeedback",
  METADATA: "api/admin/getMetadata",
  NOTIFICATION: "/api/admin/getNotificationV2",
  FAQ: "api/admin/getFaq",
  PARTNERS: "api/admin/getPartners",
  WELCOME_ALL: "api/welcome/all",
  WELCOME: "api/welcome",
  CATEGORY_SAVE: "api/category",
  CATEGORY_DELETE: "api/category/deleteCategory",
  CATEGORY_BY_ID: "api/category/getCategoryByID",
  REFERRAL: "api/admin/getRewardFactor",
  JOB_REFERRAL: "api/job-portal/get-job-referral",
  JOB_ALL: "api/job-portal/all-jobs",
  JOB_APPLICANTS: "api/job-portal/job-applicants/",
  JOB_DELETE: "api/job-portal/delete-job",
  CREATE_FAQ: "api/admin/createFaq",
  DELETE_FAQ: "api/admin/deleteFaq",
  UPDATE_FAQ: "api/admin/updateFaq",
  METADATA_UPDATE: "api/admin/updateMetadata",
  REWARD_FACTOR: "api/admin/getRewardFactor",
  REWARD_FACTOR_UPDATE: "api/admin/updateRewardFactor",
  POST_JOB: "api/job-portal/post-job",
  UPDATE_JOB: "api/job-portal/update-job/",
  SOCIAL_MEDIA: "api/admin/getSocialMedia",
  ADD_SOCIAL_MEDIA: "api/admin/createSocialMediaNew",
  DELETE_SOCIAL_MEDIA: "api/admin/deleteSocialMedia",
  UPDATE_FEEDBACK: "api/admin/updateFeedback",
  LIST_SUBADMINS: "/api/user//getSubAdmins",
  SAVE_VIDEO: "api/admin/saveVideoByAdmin",
  DELETE_VIDEO: "api/video/deleteVideo",
  UPDATE_VIDEO_STATUS: "api/video/updateVideoStatus",
  SEND_PUSH_NOTIFICATION: "api/admin/sendPushNotification",
  UPDATE_USER_STATUS: "api/user/updateUserStatus",
  CATEGORY_VIDEOS: "api/categoryvideos/getAllVideosByCategory",
  CATEGORY_VIDEOS_V2: "api/categoryvideos/getAllVideosByCategoryV2",
  CATEGORY_VIDEOS_SAVE: "api/categoryvideos",
  CATEGORY_VIDEOS_UPDATE: "api/categoryvideos/updateVideoStatus",
  CATEGORY_VIDEOS_DELETE: "api/categoryvideos/deleteVideo",
  QUESTION: "api/question",
  QUESTION_BY_VIDEO_ID: "api/question/ByVedioId",
  QUESTION_DELETE: "api/question/deleteQuestion",
  PARTNER_STATUS: "api/admin/updatePartnerStatus",
  PARTNER_DELETE: "api/admin/deletePartner",
  CREATE_PARTNER: "api/admin/createPartnerNew",
  UPDATE_PARTNER: "api/admin/updatePartnerNew",
  UPDATE_PROFILE_PHOTO: "api/user/updateProfilePhoto",
  CATEGORY_LIST_ITEMS: "api/category/getCategoryListItems",
  ADD_CATEGORY_LIST_ITEM: "api/category/addCategoryListItem",
  DELETE_CATEGORY_LIST_ITEM: "api/category/deleteCategoryListItem",
  UPDATE_CATEGORY_LIST_ITEM: "api/category/updateCategoryListItem",
  ADD_DELETED_USER: "api/admin/addDeletedUser",
  GET_DELETED_USERS: "api/admin/getDeletedUsers",
  DELETE_USER: "api/admin/deleteUser",
  UPDATE_SUBADMIN: "/api/user/updateSubAdmin/",
  CREATE_SUBADMIN: "api/user/createsubadmin/",
  UPDATE_ADMIN_PASSWORD: "/api/admin/updateAdminPassword",
  DELETE_SUBADMIN:"/api/user/deletesubadmin/",
  FETCH_PERMISSIONS:"/api/subadmin/fetchpermissions/",
  HISTORY_SUBADMIN:"api/subadmin/getroutehistory/",
  GIVE_PERMISSIONS:"api/subadmin/givepermissions/",
  USER_REQUEST: "api/user/getpendinguserreq",
  VIDEO_REQUEST: "api/video/getpendinguserreq",
  PARTNER_REQUEST: "api/admin/getPendingPartner",
  SOCIAL_MEDIA_REQUEST: "api/admin/getPendingSocialMedia",
  TEST_API: "/api/Video/getVideosByCategoryName",
  PENDING_CATEGORY: "api/category/getPendingCategory",
  COMPLETE_REGISTRATION:"api/enterprise/complete-profile",
  COMPLETE:"api/enterprise/completed",
  ALL_EMPLOYEES:"api/enterprise/getEmployees",
  ENTERPRISE_DETAILS:"api/enterprise/getUserDetails", 
  CATEGORY_ENTERPRISE:"api/category/getCategoryEnterprise",
  ADD_CATEGORY_ENTERPRISE:"api/category/addCategoryEnterprise",
  ADD_VIDEO_ENTERPRISE:"api/categoryvideos/",
  ENTERPRISE_JOBS:"api/job-portal/getAllJobsEnterprise",
  ENTERPRISE_KIND:"api/category/getCategoryByKind",
  CATEGORY_EMPLOYEES:"api/enterprise/getPermissionCategories",
  FETCH_COURSE_PERMISSIONS:"api/enterprise/fetchPermissions",
  UPDATE_COURSE_PERMISSIONS:"api/enterprise/updatePermissions",
  SECTION_PERMISSIONS:"/api/enterprise/giveSectionPermissions",
  ENTERPRISE_ADMINS:"api/enterprise/all-users",
  ENTERPRISE_EMPLOYEES:"api/enterprise/EnterpriseEmployees",
  SIGNOUTALL:"api/enterprise/signout-all",
  CATEGORY_DETAILS:"api/enterprise/getCategoriesData",
  };
  